baseURL = "https://cloudfy.netlify.app/"
languageCode = "en-us"
title = "Doctopus Blog"
theme = "hugo-theme-novela"
[social]
twitter= "https://twitter.com/DocTapas"
github= "https://github.com/doctopus"
